### ISSUE TITLE
IfcAxis2Placement2D.LocationIsCP error

### ISSUE THREAD

**Issue by RickBrice** [buildingSMART/validate#6]
This is more of a question and not an issue, but this repo doesn't have a discussion board, so I'll post here - please redirect me to the appropriate forum. 

I'm trying the validation service for the first time and I'm getting an error I don't understand. 

![image](https://github.com/buildingSMART/validate/assets/37087370/f4628830-5d3d-4a8d-a5f8-4a74ea2c5e21)

Here are the relavent lines from my file

![image](https://github.com/buildingSMART/validate/assets/37087370/f5cfbce5-9ed3-4d74-8ba2-4697054870ae)

It seems to me that the rule is testing that IfcAxis2Placement2D.Location is an IfcCartesianPoint, which it is so I don't see a violation.

What about this am I not understanding? Thanks.

**Comment by aothms** [comment]
Oh dear, this is either a consequence of https://github.com/IfcOpenShell/IfcOpenShell/issues/3126 or there is something really funky going on with the file. Thanks for the report. I'll have a look.

    ifc4x3.ifccartesianpoint in {ifc4x3_add1.ifcpoint, ifc4x3_add1.ifccartesianpoint, ...}
    ^^^^^^                                             ^^^^^^^^^^^

**Comment by RickBrice** [comment]
There are several other errors emitted the validator, but they all take basically the same format. Here is a link to the source file.

[https://github.com/RickBrice/IfcAlignmentDriver/blob/master/TestFiles/HorizontalCurves/HC_N0E_Left_3a.ifc]()

**Comment by aothms** [comment]
This fixed now and deployed. Thanks again for the report.
