### ISSUE TITLE
Possible validation error with Spatial Breakdown Structure for bridges

### ISSUE THREAD

**Issue by RickBrice** [buildingSMART/validate#61]
It has been recommended to me to log this discussion as a possible error with the validation service; See https://github.com/jwouellette/TPF-5_372-Unit_Test_Suite/issues/14

I don't know if it is a true error or not.

The root cause seems to be `IfcBridgePart` decomposed by `IfcBridgePart`. This decomposition is not provided in the csv table, so I guess failing the validation is technically correct. A bridge part, like a substructure, is logically decomposed by abutments and foundations without the need for IfcSpace.

Here is an example file and validation output.

[PGSuper1.ifc.txt](https://github.com/buildingSMART/validate/files/15123103/PGSuper1.ifc.txt)

![image](https://github.com/buildingSMART/validate/assets/37087370/93fa115f-8b3c-41a3-a3fd-7c8dcd1614d9)

**Comment by evandroAlfieri** [comment]
See https://github.com/jwouellette/TPF-5_372-Unit_Test_Suite/issues/14#issuecomment-2078807583

**Comment by civilx64** [comment]
@RickBrice the model was fine; there was an issue with the validation service that has been fixed in v0.6.1: 
![image](https://github.com/buildingSMART/validate/assets/26513472/4a13a120-4694-41fc-ad48-54cf1e80755c)
