### ISSUE TITLE
Blank Validator Page when following Option1 of the readme

### ISSUE THREAD

**Issue by EliottPaillard** [buildingSMART/validate#69]
Hello,
I was trying to run the validator by following the steps from Option1 with docker compose.
Each step gives the expected outcome except finally I can't use the validator.
My http://localhost then looks like this :
<img width="269" alt="image" src="https://github.com/buildingSMART/validate/assets/143092948/ecdbcedd-12fb-4cf0-a654-63b70b482a53">
Any ideas ?

**Comment by rubendecuypere** [comment]
I also got a blank page, and in the browser console, I got CORS policy related errors:

`https://dev.validate.buildingsmart.org/manifest.json' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by rw-bsi** [comment]
Hi Elliot/Ruben - thanks for raising this. 

We're working on a PR to remove the dependency to the buildingsmart.org domain from the current codebase. 
I'll ping the details here when it's ready for review.
