### ISSUE TITLE
Error message is unclear

### ISSUE THREAD

**Issue by RickBrice** [buildingSMART/validate#77]
With VS 0.6.4, I'm getting error messages I haven't seen before and the meaning is unclear to me.

Here are the messages
![image](https://github.com/buildingSMART/validate/assets/37087370/8d12da56-7056-48ec-b829-f873faee8434)

The file is attached.

[FHWA_Bridge_Geometry_Alignment_Example.ifc.txt](https://github.com/user-attachments/files/16152152/FHWA_Bridge_Geometry_Alignment_Example.ifc.txt)

What does the error mean? How might it be resolved?

The units definitions seem to conform to the IFC 2x Edition 3 Model Implementation Guide by T. Liebich, May 18, 2009 https://standards.buildingsmart.org/documents/Implementation/IFC2x_Model_Implementation_Guide_V2-0b.pdf

**Comment by civilx64** [comment]
As you mentioned in IfcOpenShell/IfcOpenShell#4998 changing the `$` to `*` will result in a passing validation.  

Copying the screenshot of the documentation for [IfcSIUnit](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcSIUnit.htm) illustrating the value being derived in IfcNamedUnit which is a subtype of IfcSIUnit.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/26513472/608fbfa3-abd9-427d-ae40-db76aee7f01d)

**Comment by RickBrice** [comment]
Thanks for the feedback.

Two, hopefully constructive, comments:

1. How is the reader supposed to know what "This attribute is formally derived." means? That term doesn't seem to be defined in the documentation. How is the reader supposed to know that an * should be encoded in the file (perhaps the STEP specification covers this)?
2. The VS error message might be more helpful if it said something to the effect "Attribute is derived in subtype. Expect * but encountered $".
